# testing file for Travis
# https://travis-ci.org/neuropoly/spinalcordtoolbox

sudo: false  # To use travis container infrastructure

language: python

notifications:
  slack: neuropoly:YA3mt28aeHN3A0Iu7RvMFigK
    on_success:change
    on_failure:always

# this enables to avoid recompilation of dipy if it was already compiled previously
cache:
  directories:
    - ${HOME}/.cache/pip

matrix:
  include:
    - os: linux
      python: 2.7  # these are just to make travis's UI a bit prettier
      env:
        - MINICONDA="Linux-x86_64"
    - os: osx
      language: generic
      env:
        - MINICONDA="MacOSX-x86_64"

before_install:
  - echo "HOME="
  - echo $HOME
  # Install miniconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-${MINICONDA}.sh -O miniconda.sh
  - export PATH=${HOME}/miniconda/bin:$PATH
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - conda update --yes conda
  # Install requirements
  - cd install/requirements/
  - ./requirements.sh
  - cd ../..

install:
# SCT: set PATH
  - SCT_DIR="${HOME}/build/neuropoly/spinalcordtoolbox"
  - PATH=${PATH}:${SCT_DIR}/bin
  - PATH=${PATH}:${SCT_DIR}/bin/linux
  - export SCT_DIR PATH
  - . ~/.bashrc
# SCT: create links
  - ./install/create_links.sh -a
# SCT: compile external packages
#  - cd external/denoise/ornlm
#  - python setup.py build_ext --inplace
#  - cd ../../../
  install/compile_external.py
  #- export PYTHONPATH=${PYTHONPATH}:${SCT_DIR}/external/denoise/ornlm

script:
  - sct_check_dependences   # test dependences
  - sct_testing -d 1  # test functions & integrity
  - cd install
  - python create_package.py -s linux  # test package creation
  - cd ../spinalcordtoolbox_v*
  - python installer.py -p ~/  # test installation of package
  - echo "DONE"
