language: python
python:
  - 2.7

install:

# Setup anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda

# The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

  - ./requirements/requirements.sh
  #- pip install nibabel

  - SCT_DIR="/home/travis/build/neuropoly/spinalcordtoolbox"
  - PATH=${PATH}:${SCT_DIR}/scripts
  - PATH=${PATH}:${SCT_DIR}/bin/debian

  # ANTS PATH
  - PATH=${PATH}:${SCT_DIR}/install/debian/ants

  # C3D PATH
  - PATH=${PATH}:${SCT_DIR}/install/debian/c3d

  # The next couple lines fix a crash with multiprocessing on Travis
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
  - travis_retry sudo apt-get install -qq --no-install-recommends fsl 
  - travis_retry sudo apt-get install -qq fsl-atlases
  - source /etc/fsl/fsl.sh

  - export SCT_DIR PATH
  - . ~/.bashrc
  - cd testing/sct_register_to_template

script:
  - python ../../scripts/sct_check_dependences.py
  #- travis_wait 
  #- python test_all.py
  - . ./test_sct_register_to_template.py
  - cat sct_register_to_template.log
