# testing file for Travis
# https://travis-ci.org/neuropoly/spinalcordtoolbox

sudo: false  # To use travis container infrastructure

language: python

notifications:
  slack: neuropoly:YA3mt28aeHN3A0Iu7RvMFigK
    on_success:change
    on_failure:always

# this enables to avoid recompilation of dipy if it was already compiled previously
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - os: linux
      python: 2.7
      env:
        - MINICONDA="Linux-x86_64"
        - PYTHONPATH="/home/travis/build/neuropoly/spinalcordtoolbox/external/denoise/ornlm"
    - os: osx
      python: 2.7
      env:
        - MINICONDA="MacOSX-x86_64"

before_install:
  - echo "HOLA!"
  # Install miniconda
  - ldd --version
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-${MINICONDA}.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - cd install/requirements/
  # Install conda requirements
  - conda install --yes --file requirementsConda.txt
  - pip install nibabel==2.0.1
  - pip install dipy==0.9.2
  # pre-built version of dipy for faster installation
#  - pip install -f https://wheels.scipy.org -U --pre dipy --no-compile
  - cd ../..

install:
# SCT: set PATH
  - SCT_DIR="/home/travis/build/neuropoly/spinalcordtoolbox"
  - PATH=${PATH}:${SCT_DIR}/bin
  - PATH=${PATH}:${SCT_DIR}/bin/linux
  - export SCT_DIR PATH
  - . ~/.bashrc

# SCT: create links
  - ./install/create_links.sh -a

# SCT: compile external packages
  - python install/compile_external.py
  #- export PYTHONPATH=${PYTHONPATH}:${SCT_DIR}/external/denoise/ornlm

script:
  - sct_check_dependences   # test dependences
  - sct_testing -d 1  # test functions & integrity
  - cd install
  - python create_package.py -s linux  # test package creation
  - cd ../spinalcordtoolbox_v*
  - python installer.py -p ~/  # test installation of package
  - echo "DONE"
