language: python
python:
  - 2.7

sudo: false
language: python

notifications:
  slack: neuropoly:YA3mt28aeHN3A0Iu7RvMFigK
    on_success:change
    on_failure:always

cache:
  directories:
    - $HOME/.cache/pip

#env:
#    global:
#        - DEPENDS="cython numpy scipy matplotlib h5py nibabel cvxopt"

#python:
#    - 2.6
#    - 3.2
#    - 3.3
#    - 3.4

#matrix:
#  include:
#    - python: 2.7
#      env:
#        - COVERAGE=1
#        - echo "JULIEN_TEST: 0"
    # To test minimum dependencies
#    - python: 2.7
#      env:
#        - COVERAGE=1
#        - DEPENDS="cython==0.18 numpy==1.6.0 scipy==0.9.0 nibabel==1.2.0"
#        - echo "JULIEN_TEST: 1"
#    - python: 2.7
#      env:
#        - DEPENDS="cython numpy==1.9.2 scipy==0.16.0 sympy==0.7.6 matplotlib==1.4.3 nibabel==2.0.1 dipy scikit_image"
#        - echo "JULIEN_TEST: 2"

#before_install:
#    - source install/travis_tools.sh
#    - virtualenv --python=python venv
#    - source venv/bin/activate
#    - python --version  # just to check
#    - retry pip install nose  # always
#    - wheelhouse_pip_install $DEPENDS
#    - if [ "${COVERAGE}" == "1" ]; then
#      pip install coverage;
#      pip install coveralls;
#      fi

before_install:
  # Install Anaconda
  - ldd --version
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - cd install/requirements/
  # Install conda requirements
  - conda install --yes --file requirementsConda.txt
  - pip install nibabel==2.0.1
  # pre-built version of dipy for faster installation
  - pip install -f https://wheels.scipy.org -U --pre dipy --no-compile
  - cd ../..

install:
# SCT: set PATH
  - SCT_DIR="/home/travis/build/neuropoly/spinalcordtoolbox"
  - PATH=${PATH}:${SCT_DIR}/bin
  - PATH=${PATH}:${SCT_DIR}/bin/linux
  - export SCT_DIR PATH
  - . ~/.bashrc

# SCT: create links
  - ./install/create_links.sh -a

# SCT: compile external packages
  - ./install/compile_external.py
  - . ~/.bashrc

script:
  - sct_check_dependences   # test dependences
  - sct_testing -d 1  # test functions & integrity
  - cd install
  - python create_package.py -s linux  # test package creation
  - cd ../spinalcordtoolbox_v*
  - python installer.py -p ~/  # test installation of package
  - echo "DONE"
